backend:
  # name: git-gateway
  name: github
  repo: nikkiselev/personal-website
  branch: redesign
media_folder: public/img
public_folder: img
collections:
  - name: 'Home'
    label: 'Home'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.json'
        fields:
          - label: 'Jobs'
            name: 'jobs'
            widget: list
            fields:
              - { label: 'Role', name: 'role', widget: 'string' }
              - { label: 'Type', name: 'type', widget: 'string' }
              - { label: 'Company', name: 'company', widget: 'string' }
              - { label: 'Place', name: 'place', widget: 'string' }
              - { label: 'From', name: 'from', widget: 'string' }
              - { label: 'To', name: 'to', widget: 'string' }
              - {
                  label: 'Responsibilitties',
                  name: 'responsibilities',
                  widget: 'list',
                  field:
                    {
                      label: 'Responsibility',
                      name: 'responsibility',
                      widget: 'string',
                    },
                }
              - {
                  label: 'Skills',
                  name: 'skills',
                  widget: 'list',
                  field: { label: 'Skill', name: 'skill', widget: 'string' },
                }
